site_name: Raphael Fanti - Portfolio
site_url: https://raphafanti.github.io/portfolio/

nav:
  - Featured projects: index.md
  - Projects by topic: projects.md
  - Blog: blog/index.md
  - About Raphael: about.md

theme:
    name: material
    favicon: img/favicon.png
    logo: img/favicon.png
    features:
        - search.suggest
    icon:
        admonition:
            note: material/test-tube
   
plugins:
    - tags:
        tags_file: projects.md
    - glightbox
    - search
    - blog
        
markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg